# Generated by Django 4.2.17 on 2025-01-14 09:40

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('notice', models.TextField()),
                ('start_publish', models.DateTimeField()),
                ('stop_publish', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('application/csv', 'application/csv'), ('application/doc', 'application/doc'), ('application/pdf', 'application/pdf'), ('application/xls', 'application/xls'), ('application/xlsx', 'application/xlsx'), ('application/xml', 'application/xml'), ('application/zip', 'application/zip'), ('image/jpeg', 'image/jpeg'), ('image/gif', 'image/gif'), ('image/png', 'image/png'), ('text/html', 'text/html'), ('text/plain', 'text/plain')], default='application/csv', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('storage_duration', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=50)),
                ('update_by', models.CharField(db_index=True, default='system', max_length=254)),
                ('application_name', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content_txt', models.TextField()),
                ('content_html', models.TextField()),
                ('receiver_person_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('receiver_email', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(editable=False)),
                ('sent', models.DateTimeField(null=True)),
                ('reference', models.CharField(db_index=True, default='', max_length=100)),
                ('show_to_user', models.BooleanField(default=True)),
                ('read_by_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageQueueCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('changed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('transaction_id', models.UUIDField(unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'outbox',
            },
        ),
        migrations.CreateModel(
            name='QueueException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.JSONField(null=True)),
                ('exception_title', models.CharField(max_length=255)),
                ('exception', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('template', ckeditor.fields.RichTextField()),
                ('format', models.CharField(choices=[('PLAIN', 'plain'), ('HTML', 'HTML'), ('PLAIN_HTML', 'plain_and_html')], max_length=15)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='ru', max_length=30)),
            ],
            options={
                'unique_together': {('reference', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('transaction_id', models.UUIDField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Done'), ('ERROR', 'Error'), ('DEAD_LETTER', 'Dead letter')], default='PENDING', max_length=15)),
                ('last_execution_date', models.DateTimeField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, default='')),
                ('attempts_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'inbox',
                'unique_together': {('consumer', 'transaction_id')},
            },
        ),
        migrations.AddConstraint(
            model_name='documentfile',
            constraint=models.CheckConstraint(check=models.Q(('content_type__in', ['application/csv', 'application/doc', 'application/pdf', 'application/xls', 'application/xlsx', 'application/xml', 'application/zip', 'image/jpeg', 'image/gif', 'image/png', 'text/html', 'text/plain'])), name='osis_common_documentfile_content_type_valid'),
        ),
    ]
